export default {
    MonthlyTradingChangesOp: {
        '去年同期成交量': 'lastyearVolume',
        '上月成交量': 'lastMonthVolume',
        '当月成交量': 'volume',
        '去年同期成交额': 'lastYearAmount',
        '上月成交额': 'lastMonthAmount',
        '当月成交额': 'amount',
        '今年累计成交总量': 'totalVolume',
        '去年同期成交总量': 'lastYearTotalVolume',
        '今年累计成交总额': 'totalAmount',
        '去年同期成交总额': 'lastYearTotalAmount',
        '本月末持仓量': 'position',
        '上月末持仓量': 'lastMonthPosition',
    },
    GetVolumeRankingsOp: {
        '成交量排名': 'volume',
        '比上交易日增减': 'volumeChange',
        '交易日期': 'tradingDate'
    },
    GetExchangeMonthlyTradingOp: {
        '去年同期成交量': 'lastYearVolume',
        '上月成交量': 'lastMonthVolume',
        '当月成交量': 'volume',
        '去年同期成交额': 'lastYearAmount',
        '上月成交额': 'lastMonthAmount',
        '当月成交额': 'amount',
        '今年累计成交总量': 'totalVolume',
        '去年同期成交总量': 'lastYearTotalVolume',
        '今年累计成交总额': 'totalAmount',
        '去年同期成交总额': 'lastYearTotalAmount',
        '本月末持仓量': 'position',
        '上月末持仓量': 'lastMonthPosition',
        '本月成交量占全国份额': 'volumeShare',
        '本月交易额占全国份额': 'amountShare',
        '今年累计成交总量占全国份额': 'totalVolumeShare',
        '今年累计成交总额占全国份额': 'totalAmountShare',
        '本月月末持仓量占全国份额': 'positionShare',
    },
    GetBondPositionRankingsOp: {
        '多头持仓机构简称':'longShortName',
        '多头持仓数量':'longNumber',
        '多头持仓增减':'longChange',
        '多头持仓占比':'longRatio',
        '持净多单机构':'netLongShortName',
        '净多单数量':'netLongNumber',
        '净多单增减':'netLongChange',
        '持净空单机构':'netShortShortName',
        '持净空单数量':'netShortNumber',
        '净空单增减':'netShortChange',
        '多头增仓机构':'longIncreaseShortName',
        '多头增仓数量':'longIncreaseNumber',
        '多头减仓机构':'longDecreaseShortName',
        '多头减仓数量':'longDecreaseNumber',
        '空头增仓机构':'shortIncreaseShortName',
        '空头增仓数量':'shortIncreaseNumber',
        '空头减仓机构':'shortDecreaseShortName',
        '空头减仓数量':'shortDecreaseNumber',
    },
    GetMonthlyVolumeChangeOfSingleContractOp: {
        '去年同期成交量':'lastYearVolume',
        '上月成交量':'lastMonthVolume',
        '当月成交量':'volume',
        '去年同期成交额':'lastYearAmount',
        '上月成交额':'lastMonthAmount',
        '当月成交额':'amount',
        '今年累计成交总量':'totalVolume',
        '去年同期成交总量':'lastYearTotalVolume',
        '今年累计成交总额':'totalAmount',
        '去年同期成交总额':'lastYearTotalAmount',
        '本月末持仓量':'position',
        '上月末持仓量':'lastMonthPosition',

    }
}


